name: "Action"
on:
  push:
    branches:
      - "*"
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Récupération des mises à niveau.
        run: sudo apt update
      - name: Mise à niveau des dépendences.
        run: sudo apt upgrade -y
      - name: Clonage du dépôt.
        uses: actions/checkout@v4
      - name: Lecture de la version de java installée.
        run: java -version && update-java-alternatives --list
      - name: Changement de version Java vers la 21.
        run: sudo update-java-alternatives --set temurin-21-jdk-amd64
      - name: Affichage du répertoire courant.
        run: pwd && ls
      - name: Lancement de la commande "build" du Gradle Wrapper.
        run: ./gradlew build